### ISSUE TITLE
Issue with the `mint` assert in `asserts.ts`

### ISSUE THREAD

**Issue by AshenI99** [curaOS/contracts#84]
## Problem

User can own `nfts` by minting, bidding and transferring. And each user can `mint` limited number of `nfts` specified by `mints_per_address` in contract metadata. But if someone got a `nft` by bidding or transferring, it is also counts as a `mint`. Therefore actual number of mints can be lower than the value used in `assert_mints_per_address` in `utils/asserts.ts`.

Here assert is using `supply_for_owner` method to get the total mints per owner, which is the wrong value. Because `supply_for_owner` method counts all the `nfts` owned by a particular owner.
https://github.com/curaOS/contracts/blob/c3dbcb077dd03ecb6663d420273007903c53ea9b/as/cNFT/assembly/utils/asserts.ts#L73-L82

**Comment by devey** [comment]
I still disagree with adding all that overhead in `PersistentTokens` because it's using a persistent state that is not gonna be necessary after we close the minting and it increases the number of methods and lines of code in the `Class`.

I think the options are these:

1. We simply don't care. I see it as unlikely that someone will first look in the _Market_ while the minting is happening and even in that case, considering the counterpart accepts the bid while the minting is open, then yes they will have bought a token and will not be able to mint another.
2. We enforce that while minting, tokens can't be transferred. It's not that much different from the first solution, but at least we acknowledge the situation and it's taken care of in the code.
3. We create a simple `PersistenMap` where we store the number of mints per user but keep it out of `PersistentTokens` _Class_, avoid the `remove_mint_per_address` cause you can't "un-mint".

It's good that you brought this up cause I think at the moment we don't have a way to close the mint, that seems to be necessary for the first two options to work. @achrafismyname ?

**Comment by achrafismyname** [comment]
I didn't understand the option 2. But I agree with the option 1, it seems unlikely someone will transfer a token before the minting ended.

**Comment by devey** [comment]
https://github.com/curaOS/contracts/pull/85#pullrequestreview-904507400
